<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="MessagePack" Version="2.5.302" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EvTap.Api\EvTap.Api.csproj" />
    <ProjectReference Include="..\..\src\EvTap.Shared\EvTap.Shared.csproj" />
    <ProjectReference Include="..\..\src\EvTap.Shared.Contracts\EvTap.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\src\EvTap.AppHost\EvTap.AppHost.csproj" />
  </ItemGroup>

</Project>